# This Makefile is for the Tk::demos extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.24 (Revision: 72400) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: (q[BINARY_LOCATION=x86_64-linux-gnu-thread-multi/Tk804.033-PPM.tar.gz])
#

#   MakeMaker Parameters:

#     BUILD_REQUIRES => {  }
#     CONFIGURE_REQUIRES => {  }
#     DIR => []
#     EXE_FILES => [q[widget]]
#     NAME => q[Tk::demos]
#     PREREQ_PM => {  }
#     TEST_REQUIRES => {  }
#     VERSION => q[804.033]
#     XS_VERSION => q[804.033]
#     clean => { FILES=>q[ *.bak] }
#     linkext => { LINKTYPE=>q[] }
#     macro => { TKDIR=>q[..] }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = x86_64-linux-gnu-gcc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = x86_64-linux-gnu-gcc
LDDLFLAGS = -shared -L/usr/local/lib -fstack-protector-strong
LDFLAGS =  -fstack-protector-strong -L/usr/local/lib
LIBC = libc-2.27.so
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 4.9.0
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.26.1
SITEARCHEXP = /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
SO = so
VENDORARCHEXP = /usr/lib/x86_64-linux-gnu/perl5/5.26
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = Tk::demos
NAME_SYM = Tk_demos
VERSION = 804.033
VERSION_MACRO = VERSION
VERSION_SYM = 804_033
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 804.033
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = ../blib/arch
INST_SCRIPT = ../blib/script
INST_BIN = ../blib/bin
INST_LIB = ../blib/lib
INST_MAN1DIR = ../blib/man1
INST_MAN3DIR = ../blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /usr
SITEPREFIX = /usr/local
VENDORPREFIX = /usr
INSTALLPRIVLIB = /usr/share/perl/5.26
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /usr/local/share/perl/5.26.1
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /usr/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /usr/lib/x86_64-linux-gnu/perl/5.26
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /usr/lib/x86_64-linux-gnu/perl5/5.26
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /usr/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /usr/local/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /usr/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /usr/local/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /usr/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /usr/local/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /usr/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.26
PERL_ARCHLIB = /usr/lib/x86_64-linux-gnu/perl/5.26
PERL_ARCHLIBDEP = /usr/lib/x86_64-linux-gnu/perl/5.26
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL_INCDEP = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL = "/usr/bin/perl"
FULLPERL = "/usr/bin/perl"
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.26/ExtUtils/MakeMaker.pm
MM_VERSION  = 7.24
MM_REVISION = 72400

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = Tk/demos
BASEEXT = demos
PARENT_NAME = Tk
DLBASE = $(BASEEXT)
VERSION_FROM = 
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = widget
MAN3PODS = demos/widget_lib/slide.pl \
	demos/widget_lib/trace2.pl

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIBDEP)$(DFSEP)Config.pm $(PERL_INCDEP)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/Tk
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/Tk

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVEDEP    = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = demos/LabEnLabRad.pm \
	demos/images/QuitPB.xpm \
	demos/images/QuitPBa.xpm \
	demos/images/c.icon \
	demos/images/cursor.cur \
	demos/images/cursor.mask \
	demos/images/cursor.xbm \
	demos/images/dir.icon \
	demos/images/dir.mask \
	demos/images/earth.gif \
	demos/images/earthris.gif \
	demos/images/face \
	demos/images/flagdown \
	demos/images/flagup \
	demos/images/grey.25 \
	demos/images/grey.5 \
	demos/images/letters \
	demos/images/mickey.gif \
	demos/images/ned.xpm \
	demos/images/noletters \
	demos/images/page.icon \
	demos/images/page.mask \
	demos/images/pattern \
	demos/images/teapot.ppm \
	demos/widget_lib/Ball.pm \
	demos/widget_lib/HList.pl \
	demos/widget_lib/HList2.pl \
	demos/widget_lib/Plot.pm \
	demos/widget_lib/WidgetDemo.pm \
	demos/widget_lib/arrows.pl \
	demos/widget_lib/balloon.pl \
	demos/widget_lib/bind.pl \
	demos/widget_lib/bitmaps.pl \
	demos/widget_lib/bounce.pl \
	demos/widget_lib/browseentry.pl \
	demos/widget_lib/browseentry2.pl \
	demos/widget_lib/button.pl \
	demos/widget_lib/check.pl \
	demos/widget_lib/choosedir.pl \
	demos/widget_lib/clrpick.pl \
	demos/widget_lib/colors.pl \
	demos/widget_lib/cscroll.pl \
	demos/widget_lib/ctext.pl \
	demos/widget_lib/dialog1.pl \
	demos/widget_lib/dialog2.pl \
	demos/widget_lib/dirtree.pl \
	demos/widget_lib/entry1.pl \
	demos/widget_lib/entry2.pl \
	demos/widget_lib/entry3.pl \
	demos/widget_lib/filebox.pl \
	demos/widget_lib/floor.pl \
	demos/widget_lib/form.pl \
	demos/widget_lib/form_mgr.pl \
	demos/widget_lib/hello.pl \
	demos/widget_lib/hscale.pl \
	demos/widget_lib/icon.pl \
	demos/widget_lib/image1.pl \
	demos/widget_lib/image2.pl \
	demos/widget_lib/items.pl \
	demos/widget_lib/keysyms.pl \
	demos/widget_lib/labelframe.pl \
	demos/widget_lib/labels.pl \
	demos/widget_lib/labframe.pl \
	demos/widget_lib/mega.pl \
	demos/widget_lib/menbut.pl \
	demos/widget_lib/menus.pl \
	demos/widget_lib/menus2.pl \
	demos/widget_lib/msgBox.pl \
	demos/widget_lib/notebook.pl \
	demos/widget_lib/paned1.pl \
	demos/widget_lib/paned2.pl \
	demos/widget_lib/photo1.pl \
	demos/widget_lib/photo2.pl \
	demos/widget_lib/plot.pl \
	demos/widget_lib/progress.pl \
	demos/widget_lib/puzzle.pl \
	demos/widget_lib/radio.pl \
	demos/widget_lib/ruler.pl \
	demos/widget_lib/sayings.pl \
	demos/widget_lib/search.pl \
	demos/widget_lib/showVars.pl \
	demos/widget_lib/slide.pl \
	demos/widget_lib/spin.pl \
	demos/widget_lib/states.pl \
	demos/widget_lib/style.pl \
	demos/widget_lib/texts.pl \
	demos/widget_lib/trace1.pl \
	demos/widget_lib/trace2.pl \
	demos/widget_lib/transtile.pl \
	demos/widget_lib/twind.pl \
	demos/widget_lib/unicodeout.pl \
	demos/widget_lib/virtevents1.pl \
	demos/widget_lib/vscale.pl \
	demos/widtrib/Gedi.pl \
	demos/widtrib/TEMPLATE.pl \
	demos/widtrib/Tiler.pl \
	demos/widtrib/all.pl \
	demos/widtrib/cursor.pl \
	demos/widtrib/lib/npuz/Xcamel.npuz \
	demos/widtrib/npuz.pl \
	demos/widtrib/plop.pl

GCCOPT =  -Wall -Wno-implicit-int -Wno-comment -Wno-unused -D__USE_FIXED_PROTOTYPES__


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 7.24
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$$$ARGV[0], $$$$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --
CP_NONEMPTY = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'cp_nonempty' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section skipped.

# --- MakeMaker macro section:
TKDIR = ..


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:
#Tk::MMutil pasthru

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	LD="$(LD)"\
	PREFIX="$(PREFIX)"\
	PASTHRU_DEFINE='$(DEFINE) $(PASTHRU_DEFINE)'\
	PASTHRU_INC='$(INC) $(PASTHRU_INC)'


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir pure_all subdirs clean_subdirs makemakerdflt manifypods realclean_subdirs subdirs_dynamic subdirs_pure_nolink subdirs_static subdirs-test_dynamic subdirs-test_static test_dynamic test_static



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)

pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: 
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) config $(INST_BOOT) $(INST_DYNAMIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--" --center "perl/Tk Documentation" --release "Tk$(VERSION)"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all config  \
	demos/widget_lib/slide.pl \
	demos/widget_lib/trace2.pl \
	widget
	$(NOECHO) $(POD2MAN) --section=$(MAN1EXT) --perm_rw=$(PERM_RW) -u \
	  widget $(INST_MAN1DIR)/widget.$(MAN1EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  demos/widget_lib/slide.pl $(INST_MAN3DIR)/Tk::demos::widget_lib::slide.$(MAN3EXT) \
	  demos/widget_lib/trace2.pl $(INST_MAN3DIR)/Tk::demos::widget_lib::trace2.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:

EXE_FILES = widget

pure_all :: $(INST_SCRIPT)/widget
	$(NOECHO) $(NOOP)

realclean ::
	$(RM_F) \
	  $(INST_SCRIPT)/widget 

$(INST_SCRIPT)/widget : widget $(FIRST_MAKEFILE) $(INST_SCRIPT)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists
	$(NOECHO) $(RM_F) $(INST_SCRIPT)/widget
	$(CP) widget $(INST_SCRIPT)/widget
	$(FIXIN) $(INST_SCRIPT)/widget
	-$(NOECHO) $(CHMOD) $(PERM_RWX) $(INST_SCRIPT)/widget



# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  $(BASEEXT).bso $(BASEEXT).def \
	  $(BASEEXT).exp $(BASEEXT).x \
	  $(BOOTSTRAP) $(INST_ARCHAUTODIR)/extralibs.all \
	  $(INST_ARCHAUTODIR)/extralibs.ld $(MAKE_APERL_FILE) \
	  *$(LIB_EXT) *$(OBJ_EXT) \
	  *perl.core MYMETA.json \
	  MYMETA.yml blibdirs.ts \
	  core core.*perl.*.? \
	  core.[0-9] core.[0-9][0-9] \
	  core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] \
	  core.[0-9][0-9][0-9][0-9][0-9] lib$(BASEEXT).def \
	  mon.out perl \
	  perl$(EXE_EXT) perl.exe \
	  perlmain.c pm_to_blib \
	  pm_to_blib.ts so_locations \
	  tmon.out 
	- $(RM_RF) \
	   *.bak \
	  blib 
	  $(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
# so clean is forced to complete before realclean_subdirs runs
realclean_subdirs : clean
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge :: realclean_subdirs
	- $(RM_F) \
	  $(FIRST_MAKEFILE) $(MAKEFILE_OLD) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '---' > META_new.yml
	$(NOECHO) $(ECHO) 'abstract: unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:' >> META_new.yml
	$(NOECHO) $(ECHO) '  - unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'dynamic_config: 1' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: '\''ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'license: unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '  url: http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '  version: '\''1.4'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'name: Tk-demos' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '  directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '    - t' >> META_new.yml
	$(NOECHO) $(ECHO) '    - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'version: '\''804.033'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'x_serialization_backend: '\''CPAN::Meta::YAML version 0.018'\''' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml
	$(NOECHO) $(ECHO) Generating META.json
	$(NOECHO) $(ECHO) '{' > META_new.json
	$(NOECHO) $(ECHO) '   "abstract" : "unknown",' >> META_new.json
	$(NOECHO) $(ECHO) '   "author" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "unknown"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "dynamic_config" : 1,' >> META_new.json
	$(NOECHO) $(ECHO) '   "generated_by" : "ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010",' >> META_new.json
	$(NOECHO) $(ECHO) '   "license" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "unknown"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "meta-spec" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",' >> META_new.json
	$(NOECHO) $(ECHO) '      "version" : "2"' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "name" : "Tk-demos",' >> META_new.json
	$(NOECHO) $(ECHO) '   "no_index" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "directory" : [' >> META_new.json
	$(NOECHO) $(ECHO) '         "t",' >> META_new.json
	$(NOECHO) $(ECHO) '         "inc"' >> META_new.json
	$(NOECHO) $(ECHO) '      ]' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "prereqs" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "build" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "configure" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      }' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "release_status" : "stable",' >> META_new.json
	$(NOECHO) $(ECHO) '   "version" : "804.033",' >> META_new.json
	$(NOECHO) $(ECHO) '   "x_serialization_backend" : "JSON::PP version 2.27400_02"' >> META_new.json
	$(NOECHO) $(ECHO) '}' >> META_new.json
	-$(NOECHO) $(MV) META_new.json $(DISTVNAME)/META.json


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section skipped.

# --- MakeMaker dist_core section skipped.

# --- MakeMaker distdir section skipped.

# --- MakeMaker dist_test section skipped.

# --- MakeMaker dist_ci section skipped.

# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -e q{META.yml};' \
	  -e 'eval { maniadd({q{META.yml} => q{Module YAML meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.yml to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -f q{META.json};' \
	  -e 'eval { maniadd({q{META.json} => q{Module JSON meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.json to MANIFEST: $${'\''@'\''}"' --



# --- MakeMaker distsignature section:
distsignature : distmeta
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section skipped.

# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP) /home/german/pruebas/PolyPrimer/src/Tk-804.033/Tk/Config.pm /home/german/pruebas/PolyPrimer/src/Tk-804.033/Tk/MMutil.pm
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL "BINARY_LOCATION=x86_64-linux-gnu-thread-multi/Tk804.033-PPM.tar.gz"
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = ../perl
FULLPERL      = "/usr/bin/perl"
MAP_PERLINC   = "-I../blib/arch" "-I../blib/lib" "-I/usr/lib/x86_64-linux-gnu/perl/5.26" "-I/usr/share/perl/5.26"


# --- MakeMaker test section:
TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = 
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)
	$(NOECHO) $(NOOP)

test :: $(TEST_TYPE)
	$(NOECHO) $(NOOP)

# Occasionally we may face this degenerate target:
test_ : test_dynamic
	$(NOECHO) $(NOOP)

subdirs-test_dynamic :: dynamic pure_all

testdb_dynamic test_dynamic :: subdirs-test_dynamic
	$(NOECHO) $(ECHO) 'No tests defined for $(NAME) extension.'

subdirs-test_static :: static pure_all

testdb_static test_static :: subdirs-test_static
	$(NOECHO) $(ECHO) 'No tests defined for $(NAME) extension.'



# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="Tk-demos" VERSION="804.033">' > Tk-demos.ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '    <AUTHOR></AUTHOR>' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="x86_64-linux-gnu-thread-multi-5.26" />' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> Tk-demos.ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> Tk-demos.ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'demos/LabEnLabRad.pm' '$(INST_LIB)/Tk/demos/LabEnLabRad.pm' \
	  'demos/images/QuitPB.xpm' '$(INST_LIB)/Tk/demos/images/QuitPB.xpm' \
	  'demos/images/QuitPBa.xpm' '$(INST_LIB)/Tk/demos/images/QuitPBa.xpm' \
	  'demos/images/c.icon' '$(INST_LIB)/Tk/demos/images/c.icon' \
	  'demos/images/cursor.cur' '$(INST_LIB)/Tk/demos/images/cursor.cur' \
	  'demos/images/cursor.mask' '$(INST_LIB)/Tk/demos/images/cursor.mask' \
	  'demos/images/cursor.xbm' '$(INST_LIB)/Tk/demos/images/cursor.xbm' \
	  'demos/images/dir.icon' '$(INST_LIB)/Tk/demos/images/dir.icon' \
	  'demos/images/dir.mask' '$(INST_LIB)/Tk/demos/images/dir.mask' \
	  'demos/images/earth.gif' '$(INST_LIB)/Tk/demos/images/earth.gif' \
	  'demos/images/earthris.gif' '$(INST_LIB)/Tk/demos/images/earthris.gif' \
	  'demos/images/face' '$(INST_LIB)/Tk/demos/images/face' \
	  'demos/images/flagdown' '$(INST_LIB)/Tk/demos/images/flagdown' \
	  'demos/images/flagup' '$(INST_LIB)/Tk/demos/images/flagup' \
	  'demos/images/grey.25' '$(INST_LIB)/Tk/demos/images/grey.25' \
	  'demos/images/grey.5' '$(INST_LIB)/Tk/demos/images/grey.5' \
	  'demos/images/letters' '$(INST_LIB)/Tk/demos/images/letters' \
	  'demos/images/mickey.gif' '$(INST_LIB)/Tk/demos/images/mickey.gif' \
	  'demos/images/ned.xpm' '$(INST_LIB)/Tk/demos/images/ned.xpm' \
	  'demos/images/noletters' '$(INST_LIB)/Tk/demos/images/noletters' \
	  'demos/images/page.icon' '$(INST_LIB)/Tk/demos/images/page.icon' \
	  'demos/images/page.mask' '$(INST_LIB)/Tk/demos/images/page.mask' \
	  'demos/images/pattern' '$(INST_LIB)/Tk/demos/images/pattern' \
	  'demos/images/teapot.ppm' '$(INST_LIB)/Tk/demos/images/teapot.ppm' \
	  'demos/widget_lib/Ball.pm' '$(INST_LIB)/Tk/demos/widget_lib/Ball.pm' \
	  'demos/widget_lib/HList.pl' '$(INST_LIB)/Tk/demos/widget_lib/HList.pl' \
	  'demos/widget_lib/HList2.pl' '$(INST_LIB)/Tk/demos/widget_lib/HList2.pl' \
	  'demos/widget_lib/Plot.pm' '$(INST_LIB)/Tk/demos/widget_lib/Plot.pm' \
	  'demos/widget_lib/WidgetDemo.pm' '$(INST_LIB)/Tk/demos/widget_lib/WidgetDemo.pm' \
	  'demos/widget_lib/arrows.pl' '$(INST_LIB)/Tk/demos/widget_lib/arrows.pl' \
	  'demos/widget_lib/balloon.pl' '$(INST_LIB)/Tk/demos/widget_lib/balloon.pl' \
	  'demos/widget_lib/bind.pl' '$(INST_LIB)/Tk/demos/widget_lib/bind.pl' \
	  'demos/widget_lib/bitmaps.pl' '$(INST_LIB)/Tk/demos/widget_lib/bitmaps.pl' \
	  'demos/widget_lib/bounce.pl' '$(INST_LIB)/Tk/demos/widget_lib/bounce.pl' \
	  'demos/widget_lib/browseentry.pl' '$(INST_LIB)/Tk/demos/widget_lib/browseentry.pl' \
	  'demos/widget_lib/browseentry2.pl' '$(INST_LIB)/Tk/demos/widget_lib/browseentry2.pl' \
	  'demos/widget_lib/button.pl' '$(INST_LIB)/Tk/demos/widget_lib/button.pl' \
	  'demos/widget_lib/check.pl' '$(INST_LIB)/Tk/demos/widget_lib/check.pl' 
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'demos/widget_lib/choosedir.pl' '$(INST_LIB)/Tk/demos/widget_lib/choosedir.pl' \
	  'demos/widget_lib/clrpick.pl' '$(INST_LIB)/Tk/demos/widget_lib/clrpick.pl' \
	  'demos/widget_lib/colors.pl' '$(INST_LIB)/Tk/demos/widget_lib/colors.pl' \
	  'demos/widget_lib/cscroll.pl' '$(INST_LIB)/Tk/demos/widget_lib/cscroll.pl' \
	  'demos/widget_lib/ctext.pl' '$(INST_LIB)/Tk/demos/widget_lib/ctext.pl' \
	  'demos/widget_lib/dialog1.pl' '$(INST_LIB)/Tk/demos/widget_lib/dialog1.pl' \
	  'demos/widget_lib/dialog2.pl' '$(INST_LIB)/Tk/demos/widget_lib/dialog2.pl' \
	  'demos/widget_lib/dirtree.pl' '$(INST_LIB)/Tk/demos/widget_lib/dirtree.pl' \
	  'demos/widget_lib/entry1.pl' '$(INST_LIB)/Tk/demos/widget_lib/entry1.pl' \
	  'demos/widget_lib/entry2.pl' '$(INST_LIB)/Tk/demos/widget_lib/entry2.pl' \
	  'demos/widget_lib/entry3.pl' '$(INST_LIB)/Tk/demos/widget_lib/entry3.pl' \
	  'demos/widget_lib/filebox.pl' '$(INST_LIB)/Tk/demos/widget_lib/filebox.pl' \
	  'demos/widget_lib/floor.pl' '$(INST_LIB)/Tk/demos/widget_lib/floor.pl' \
	  'demos/widget_lib/form.pl' '$(INST_LIB)/Tk/demos/widget_lib/form.pl' \
	  'demos/widget_lib/form_mgr.pl' '$(INST_LIB)/Tk/demos/widget_lib/form_mgr.pl' \
	  'demos/widget_lib/hello.pl' '$(INST_LIB)/Tk/demos/widget_lib/hello.pl' \
	  'demos/widget_lib/hscale.pl' '$(INST_LIB)/Tk/demos/widget_lib/hscale.pl' \
	  'demos/widget_lib/icon.pl' '$(INST_LIB)/Tk/demos/widget_lib/icon.pl' \
	  'demos/widget_lib/image1.pl' '$(INST_LIB)/Tk/demos/widget_lib/image1.pl' \
	  'demos/widget_lib/image2.pl' '$(INST_LIB)/Tk/demos/widget_lib/image2.pl' \
	  'demos/widget_lib/items.pl' '$(INST_LIB)/Tk/demos/widget_lib/items.pl' \
	  'demos/widget_lib/keysyms.pl' '$(INST_LIB)/Tk/demos/widget_lib/keysyms.pl' \
	  'demos/widget_lib/labelframe.pl' '$(INST_LIB)/Tk/demos/widget_lib/labelframe.pl' \
	  'demos/widget_lib/labels.pl' '$(INST_LIB)/Tk/demos/widget_lib/labels.pl' \
	  'demos/widget_lib/labframe.pl' '$(INST_LIB)/Tk/demos/widget_lib/labframe.pl' \
	  'demos/widget_lib/mega.pl' '$(INST_LIB)/Tk/demos/widget_lib/mega.pl' \
	  'demos/widget_lib/menbut.pl' '$(INST_LIB)/Tk/demos/widget_lib/menbut.pl' \
	  'demos/widget_lib/menus.pl' '$(INST_LIB)/Tk/demos/widget_lib/menus.pl' \
	  'demos/widget_lib/menus2.pl' '$(INST_LIB)/Tk/demos/widget_lib/menus2.pl' \
	  'demos/widget_lib/msgBox.pl' '$(INST_LIB)/Tk/demos/widget_lib/msgBox.pl' \
	  'demos/widget_lib/notebook.pl' '$(INST_LIB)/Tk/demos/widget_lib/notebook.pl' \
	  'demos/widget_lib/paned1.pl' '$(INST_LIB)/Tk/demos/widget_lib/paned1.pl' \
	  'demos/widget_lib/paned2.pl' '$(INST_LIB)/Tk/demos/widget_lib/paned2.pl' \
	  'demos/widget_lib/photo1.pl' '$(INST_LIB)/Tk/demos/widget_lib/photo1.pl' \
	  'demos/widget_lib/photo2.pl' '$(INST_LIB)/Tk/demos/widget_lib/photo2.pl' 
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'demos/widget_lib/plot.pl' '$(INST_LIB)/Tk/demos/widget_lib/plot.pl' \
	  'demos/widget_lib/progress.pl' '$(INST_LIB)/Tk/demos/widget_lib/progress.pl' \
	  'demos/widget_lib/puzzle.pl' '$(INST_LIB)/Tk/demos/widget_lib/puzzle.pl' \
	  'demos/widget_lib/radio.pl' '$(INST_LIB)/Tk/demos/widget_lib/radio.pl' \
	  'demos/widget_lib/ruler.pl' '$(INST_LIB)/Tk/demos/widget_lib/ruler.pl' \
	  'demos/widget_lib/sayings.pl' '$(INST_LIB)/Tk/demos/widget_lib/sayings.pl' \
	  'demos/widget_lib/search.pl' '$(INST_LIB)/Tk/demos/widget_lib/search.pl' \
	  'demos/widget_lib/showVars.pl' '$(INST_LIB)/Tk/demos/widget_lib/showVars.pl' \
	  'demos/widget_lib/slide.pl' '$(INST_LIB)/Tk/demos/widget_lib/slide.pl' \
	  'demos/widget_lib/spin.pl' '$(INST_LIB)/Tk/demos/widget_lib/spin.pl' \
	  'demos/widget_lib/states.pl' '$(INST_LIB)/Tk/demos/widget_lib/states.pl' \
	  'demos/widget_lib/style.pl' '$(INST_LIB)/Tk/demos/widget_lib/style.pl' \
	  'demos/widget_lib/texts.pl' '$(INST_LIB)/Tk/demos/widget_lib/texts.pl' \
	  'demos/widget_lib/trace1.pl' '$(INST_LIB)/Tk/demos/widget_lib/trace1.pl' \
	  'demos/widget_lib/trace2.pl' '$(INST_LIB)/Tk/demos/widget_lib/trace2.pl' \
	  'demos/widget_lib/transtile.pl' '$(INST_LIB)/Tk/demos/widget_lib/transtile.pl' \
	  'demos/widget_lib/twind.pl' '$(INST_LIB)/Tk/demos/widget_lib/twind.pl' \
	  'demos/widget_lib/unicodeout.pl' '$(INST_LIB)/Tk/demos/widget_lib/unicodeout.pl' \
	  'demos/widget_lib/virtevents1.pl' '$(INST_LIB)/Tk/demos/widget_lib/virtevents1.pl' \
	  'demos/widget_lib/vscale.pl' '$(INST_LIB)/Tk/demos/widget_lib/vscale.pl' \
	  'demos/widtrib/Gedi.pl' '$(INST_LIB)/Tk/demos/widtrib/Gedi.pl' \
	  'demos/widtrib/TEMPLATE.pl' '$(INST_LIB)/Tk/demos/widtrib/TEMPLATE.pl' \
	  'demos/widtrib/Tiler.pl' '$(INST_LIB)/Tk/demos/widtrib/Tiler.pl' \
	  'demos/widtrib/all.pl' '$(INST_LIB)/Tk/demos/widtrib/all.pl' \
	  'demos/widtrib/cursor.pl' '$(INST_LIB)/Tk/demos/widtrib/cursor.pl' \
	  'demos/widtrib/lib/npuz/Xcamel.npuz' '$(INST_LIB)/Tk/demos/widtrib/lib/npuz/Xcamel.npuz' \
	  'demos/widtrib/npuz.pl' '$(INST_LIB)/Tk/demos/widtrib/npuz.pl' \
	  'demos/widtrib/plop.pl' '$(INST_LIB)/Tk/demos/widtrib/plop.pl' 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:

# here so even if top_targets is overridden, these will still be defined
# gmake will silently still work if any are .PHONY-ed but nmake won't

static ::
	$(NOECHO) $(NOOP)

dynamic ::
	$(NOECHO) $(NOOP)

config ::
	$(NOECHO) $(NOOP)


# --- MakeMaker postamble section:


# End.
