# This Makefile is for the Tk::pod extension to perl.
#
# It was generated automatically by MakeMaker version
# 7.24 (Revision: 72400) from the contents of
# Makefile.PL. Don't edit this file, edit Makefile.PL instead.
#
#       ANY CHANGES MADE HERE WILL BE LOST!
#
#   MakeMaker ARGV: (q[BINARY_LOCATION=x86_64-linux-gnu-thread-multi/Tk804.033-PPM.tar.gz])
#

#   MakeMaker Parameters:

#     BUILD_REQUIRES => {  }
#     CONFIGURE_REQUIRES => {  }
#     NAME => q[Tk::pod]
#     PMLIBDIRS => [q[Menu]]
#     PREREQ_PM => {  }
#     TEST_REQUIRES => {  }

# --- MakeMaker post_initialize section:


# --- MakeMaker const_config section:

# These definitions are from config.sh (via /usr/lib/x86_64-linux-gnu/perl/5.26/Config.pm).
# They may have been overridden via Makefile.PL or on the command line.
AR = ar
CC = x86_64-linux-gnu-gcc
CCCDLFLAGS = -fPIC
CCDLFLAGS = -Wl,-E
DLEXT = so
DLSRC = dl_dlopen.xs
EXE_EXT = 
FULL_AR = /usr/bin/ar
LD = x86_64-linux-gnu-gcc
LDDLFLAGS = -shared -L/usr/local/lib -fstack-protector-strong
LDFLAGS =  -fstack-protector-strong -L/usr/local/lib
LIBC = libc-2.27.so
LIB_EXT = .a
OBJ_EXT = .o
OSNAME = linux
OSVERS = 4.9.0
RANLIB = :
SITELIBEXP = /usr/local/share/perl/5.26.1
SITEARCHEXP = /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
SO = so
VENDORARCHEXP = /usr/lib/x86_64-linux-gnu/perl5/5.26
VENDORLIBEXP = /usr/share/perl5


# --- MakeMaker constants section:
AR_STATIC_ARGS = cr
DIRFILESEP = /
DFSEP = $(DIRFILESEP)
NAME = Tk::pod
NAME_SYM = Tk_pod
VERSION = 
VERSION_MACRO = VERSION
VERSION_SYM = 
DEFINE_VERSION = -D$(VERSION_MACRO)=\"$(VERSION)\"
XS_VERSION = 
XS_VERSION_MACRO = XS_VERSION
XS_DEFINE_VERSION = -D$(XS_VERSION_MACRO)=\"$(XS_VERSION)\"
INST_ARCHLIB = ../blib/arch
INST_SCRIPT = ../blib/script
INST_BIN = ../blib/bin
INST_LIB = ../blib/lib
INST_MAN1DIR = ../blib/man1
INST_MAN3DIR = ../blib/man3
MAN1EXT = 1p
MAN3EXT = 3pm
INSTALLDIRS = site
DESTDIR = 
PREFIX = $(SITEPREFIX)
PERLPREFIX = /usr
SITEPREFIX = /usr/local
VENDORPREFIX = /usr
INSTALLPRIVLIB = /usr/share/perl/5.26
DESTINSTALLPRIVLIB = $(DESTDIR)$(INSTALLPRIVLIB)
INSTALLSITELIB = /usr/local/share/perl/5.26.1
DESTINSTALLSITELIB = $(DESTDIR)$(INSTALLSITELIB)
INSTALLVENDORLIB = /usr/share/perl5
DESTINSTALLVENDORLIB = $(DESTDIR)$(INSTALLVENDORLIB)
INSTALLARCHLIB = /usr/lib/x86_64-linux-gnu/perl/5.26
DESTINSTALLARCHLIB = $(DESTDIR)$(INSTALLARCHLIB)
INSTALLSITEARCH = /usr/local/lib/x86_64-linux-gnu/perl/5.26.1
DESTINSTALLSITEARCH = $(DESTDIR)$(INSTALLSITEARCH)
INSTALLVENDORARCH = /usr/lib/x86_64-linux-gnu/perl5/5.26
DESTINSTALLVENDORARCH = $(DESTDIR)$(INSTALLVENDORARCH)
INSTALLBIN = /usr/bin
DESTINSTALLBIN = $(DESTDIR)$(INSTALLBIN)
INSTALLSITEBIN = /usr/local/bin
DESTINSTALLSITEBIN = $(DESTDIR)$(INSTALLSITEBIN)
INSTALLVENDORBIN = /usr/bin
DESTINSTALLVENDORBIN = $(DESTDIR)$(INSTALLVENDORBIN)
INSTALLSCRIPT = /usr/bin
DESTINSTALLSCRIPT = $(DESTDIR)$(INSTALLSCRIPT)
INSTALLSITESCRIPT = /usr/local/bin
DESTINSTALLSITESCRIPT = $(DESTDIR)$(INSTALLSITESCRIPT)
INSTALLVENDORSCRIPT = /usr/bin
DESTINSTALLVENDORSCRIPT = $(DESTDIR)$(INSTALLVENDORSCRIPT)
INSTALLMAN1DIR = /usr/share/man/man1
DESTINSTALLMAN1DIR = $(DESTDIR)$(INSTALLMAN1DIR)
INSTALLSITEMAN1DIR = /usr/local/man/man1
DESTINSTALLSITEMAN1DIR = $(DESTDIR)$(INSTALLSITEMAN1DIR)
INSTALLVENDORMAN1DIR = /usr/share/man/man1
DESTINSTALLVENDORMAN1DIR = $(DESTDIR)$(INSTALLVENDORMAN1DIR)
INSTALLMAN3DIR = /usr/share/man/man3
DESTINSTALLMAN3DIR = $(DESTDIR)$(INSTALLMAN3DIR)
INSTALLSITEMAN3DIR = /usr/local/man/man3
DESTINSTALLSITEMAN3DIR = $(DESTDIR)$(INSTALLSITEMAN3DIR)
INSTALLVENDORMAN3DIR = /usr/share/man/man3
DESTINSTALLVENDORMAN3DIR = $(DESTDIR)$(INSTALLVENDORMAN3DIR)
PERL_LIB = /usr/share/perl/5.26
PERL_ARCHLIB = /usr/lib/x86_64-linux-gnu/perl/5.26
PERL_ARCHLIBDEP = /usr/lib/x86_64-linux-gnu/perl/5.26
LIBPERL_A = libperl.a
FIRST_MAKEFILE = Makefile
MAKEFILE_OLD = Makefile.old
MAKE_APERL_FILE = Makefile.aperl
PERLMAINCC = $(CC)
PERL_INC = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL_INCDEP = /usr/lib/x86_64-linux-gnu/perl/5.26/CORE
PERL = "/usr/bin/perl"
FULLPERL = "/usr/bin/perl"
ABSPERL = $(PERL)
PERLRUN = $(PERL)
FULLPERLRUN = $(FULLPERL)
ABSPERLRUN = $(ABSPERL)
PERLRUNINST = $(PERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
FULLPERLRUNINST = $(FULLPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
ABSPERLRUNINST = $(ABSPERLRUN) "-I$(INST_ARCHLIB)" "-I$(INST_LIB)"
PERL_CORE = 0
PERM_DIR = 755
PERM_RW = 644
PERM_RWX = 755

MAKEMAKER   = /usr/share/perl/5.26/ExtUtils/MakeMaker.pm
MM_VERSION  = 7.24
MM_REVISION = 72400

# FULLEXT = Pathname for extension directory (eg Foo/Bar/Oracle).
# BASEEXT = Basename part of FULLEXT. May be just equal FULLEXT. (eg Oracle)
# PARENT_NAME = NAME without BASEEXT and no trailing :: (eg Foo::Bar)
# DLBASE  = Basename part of dynamic library. May be just equal BASEEXT.
MAKE = make
FULLEXT = Tk/pod
BASEEXT = pod
PARENT_NAME = Tk
DLBASE = $(BASEEXT)
VERSION_FROM = 
OBJECT = 
LDFROM = $(OBJECT)
LINKTYPE = dynamic
BOOTDEP = 

# Handy lists of source code files:
XS_FILES = 
C_FILES  = 
O_FILES  = 
H_FILES  = 
MAN1PODS = 
MAN3PODS = 804delta.pod \
	Adjuster.pod \
	Animation.pod \
	Balloon.pod \
	Bitmap.pod \
	BrowseEntry.pod \
	Button.pod \
	Canvas.pod \
	Checkbutton.pod \
	Clipboard.pod \
	CmdLine.pod \
	ColorEditor.pod \
	Compound.pod \
	ConfigSpecs.pod \
	DItem.pod \
	Derived.pod \
	Dialog.pod \
	DialogBox.pod \
	DirTree.pod \
	Entry.pod \
	Error.pod \
	ErrorDialog.pod \
	Eventloop.pod \
	FBox.pod \
	FileSelect.pod \
	Font.pod \
	Frame.pod \
	HList.pod \
	IO.pod \
	IconList.pod \
	Image.pod \
	InputO.pod \
	Internals.pod \
	LabFrame.pod \
	Label.pod \
	Labelframe.pod \
	Listbox.pod \
	MainWindow.pod \
	Menu.pod \
	Menu/Item.pod \
	Menubutton.pod \
	Message.pod \
	MsgBox.pod \
	Mwm.pod \
	NoteBook.pod \
	Optionmenu.pod \
	Panedwindow.pod \
	Photo.pod \
	Pixmap.pod \
	Popup.pod \
	ROText.pod \
	Radiobutton.pod \
	Scale.pod \
	Scrollbar.pod \
	Scrolled.pod \
	Spinbox.pod \
	Submethods.pod \
	TList.pod \
	Table.pod \
	Tcl-perl.pod \
	Text.pod \
	TextUndo.pod \
	Tiler.pod \
	TixGrid.pod \
	Toplevel.pod \
	Tree.pod \
	UserGuide.pod \
	Widget.pod \
	WidgetDemo.pod \
	Wm.pod \
	X.pod \
	X11Font.pod \
	Xrm.pod \
	after.pod \
	bind.pod \
	bindtags.pod \
	callbacks.pod \
	chooseColor.pod \
	chooseDirectory.pod \
	composite.pod \
	event.pod \
	exit.pod \
	fileevent.pod \
	focus.pod \
	form.pod \
	getOpenFile.pod \
	grab.pod \
	grid.pod \
	mega.pod \
	messageBox.pod \
	option.pod \
	options.pod \
	overview.pod \
	pTk.pod \
	pack.pod \
	palette.pod \
	place.pod \
	selection.pod \
	send.pod \
	tixWm.pod \
	tkvars.pod \
	widgets.pod

# Where is the Config information that we are using/depend on
CONFIGDEP = $(PERL_ARCHLIBDEP)$(DFSEP)Config.pm $(PERL_INCDEP)$(DFSEP)config.h

# Where to build things
INST_LIBDIR      = $(INST_LIB)/Tk
INST_ARCHLIBDIR  = $(INST_ARCHLIB)/Tk

INST_AUTODIR     = $(INST_LIB)/auto/$(FULLEXT)
INST_ARCHAUTODIR = $(INST_ARCHLIB)/auto/$(FULLEXT)

INST_STATIC      = 
INST_DYNAMIC     = 
INST_BOOT        = 

# Extra linker info
EXPORT_LIST        = 
PERL_ARCHIVE       = 
PERL_ARCHIVEDEP    = 
PERL_ARCHIVE_AFTER = 


TO_INST_PM = 804delta.pod \
	Adjuster.pod \
	Animation.pod \
	Balloon.pod \
	Bitmap.pod \
	BrowseEntry.pod \
	Button.pod \
	Canvas.pod \
	Checkbutton.pod \
	Clipboard.pod \
	CmdLine.pod \
	ColorEditor.pod \
	Compound.pod \
	ConfigSpecs.pod \
	DItem.pod \
	Derived.pod \
	Dialog.pod \
	DialogBox.pod \
	DirTree.pod \
	Entry.pod \
	Error.pod \
	ErrorDialog.pod \
	Eventloop.pod \
	FBox.pod \
	FileSelect.pod \
	Font.pod \
	Frame.pod \
	HList.pod \
	IO.pod \
	IconList.pod \
	Image.pod \
	InputO.pod \
	Internals.pod \
	LabFrame.pod \
	Label.pod \
	Labelframe.pod \
	Listbox.pod \
	MainWindow.pod \
	Menu.pod \
	Menu/Item.pod \
	Menubutton.pod \
	Message.pod \
	MsgBox.pod \
	Mwm.pod \
	NoteBook.pod \
	Optionmenu.pod \
	Panedwindow.pod \
	Photo.pod \
	Pixmap.pod \
	Popup.pod \
	ROText.pod \
	Radiobutton.pod \
	Scale.pod \
	Scrollbar.pod \
	Scrolled.pod \
	Spinbox.pod \
	Submethods.pod \
	TList.pod \
	Table.pod \
	Tcl-perl.pod \
	Text.pod \
	TextUndo.pod \
	Tiler.pod \
	TixGrid.pod \
	Toplevel.pod \
	Tree.pod \
	UserGuide.pod \
	Widget.pod \
	WidgetDemo.pod \
	Wm.pod \
	X.pod \
	X11Font.pod \
	Xrm.pod \
	after.pod \
	bind.pod \
	bindtags.pod \
	callbacks.pod \
	chooseColor.pod \
	chooseDirectory.pod \
	composite.pod \
	event.pod \
	exit.pod \
	fileevent.pod \
	focus.pod \
	form.pod \
	getOpenFile.pod \
	grab.pod \
	grid.pod \
	mega.pod \
	messageBox.pod \
	option.pod \
	options.pod \
	overview.pod \
	pTk.pod \
	pack.pod \
	palette.pod \
	place.pod \
	selection.pod \
	send.pod \
	tixWm.pod \
	tkvars.pod \
	widgets.pod


# --- MakeMaker platform_constants section:
MM_Unix_VERSION = 7.24
PERL_MALLOC_DEF = -DPERL_EXTMALLOC_DEF -Dmalloc=Perl_malloc -Dfree=Perl_mfree -Drealloc=Perl_realloc -Dcalloc=Perl_calloc


# --- MakeMaker tool_autosplit section:
# Usage: $(AUTOSPLITFILE) FileToSplit AutoDirToSplitInto
AUTOSPLITFILE = $(ABSPERLRUN)  -e 'use AutoSplit;  autosplit($$$$ARGV[0], $$$$ARGV[1], 0, 1, 1)' --



# --- MakeMaker tool_xsubpp section:


# --- MakeMaker tools_other section:
SHELL = /bin/sh
CHMOD = chmod
CP = cp
MV = mv
NOOP = $(TRUE)
NOECHO = @
RM_F = rm -f
RM_RF = rm -rf
TEST_F = test -f
TOUCH = touch
UMASK_NULL = umask 0
DEV_NULL = > /dev/null 2>&1
MKPATH = $(ABSPERLRUN) -MExtUtils::Command -e 'mkpath' --
EQUALIZE_TIMESTAMP = $(ABSPERLRUN) -MExtUtils::Command -e 'eqtime' --
FALSE = false
TRUE = true
ECHO = echo
ECHO_N = echo -n
UNINST = 0
VERBINST = 0
MOD_INSTALL = $(ABSPERLRUN) -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''$(VERBINST)'\'', uninstall_shadows => '\''$(UNINST)'\'', dir_mode => '\''$(PERM_DIR)'\'' ]);' --
DOC_INSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'perllocal_install' --
UNINSTALL = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'uninstall' --
WARN_IF_OLD_PACKLIST = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'warn_if_old_packlist' --
MACROSTART = 
MACROEND = 
USEMAKEFILE = -f
FIXIN = $(ABSPERLRUN) -MExtUtils::MY -e 'MY->fixin(shift)' --
CP_NONEMPTY = $(ABSPERLRUN) -MExtUtils::Command::MM -e 'cp_nonempty' --


# --- MakeMaker makemakerdflt section:
makemakerdflt : all
	$(NOECHO) $(NOOP)


# --- MakeMaker dist section skipped.

# --- MakeMaker macro section:


# --- MakeMaker depend section:


# --- MakeMaker cflags section:


# --- MakeMaker const_loadlibs section:


# --- MakeMaker const_cccmd section:


# --- MakeMaker post_constants section:


# --- MakeMaker pasthru section:

PASTHRU = LIBPERL_A="$(LIBPERL_A)"\
	LINKTYPE="$(LINKTYPE)"\
	LD="$(LD)"\
	PREFIX="$(PREFIX)"\
	PASTHRU_DEFINE='$(DEFINE) $(PASTHRU_DEFINE)'\
	PASTHRU_INC='$(INC) $(PASTHRU_INC)'


# --- MakeMaker special_targets section:
.SUFFIXES : .xs .c .C .cpp .i .s .cxx .cc $(OBJ_EXT)

.PHONY: all config static dynamic test linkext manifest blibdirs clean realclean disttest distdir pure_all subdirs clean_subdirs makemakerdflt manifypods realclean_subdirs subdirs_dynamic subdirs_pure_nolink subdirs_static subdirs-test_dynamic subdirs-test_static test_dynamic test_static



# --- MakeMaker c_o section:


# --- MakeMaker xs_c section:


# --- MakeMaker xs_o section:


# --- MakeMaker top_targets section:
all :: pure_all manifypods
	$(NOECHO) $(NOOP)

pure_all :: config pm_to_blib subdirs linkext
	$(NOECHO) $(NOOP)

	$(NOECHO) $(NOOP)

subdirs :: $(MYEXTLIB)
	$(NOECHO) $(NOOP)

config :: $(FIRST_MAKEFILE) blibdirs
	$(NOECHO) $(NOOP)

help :
	perldoc ExtUtils::MakeMaker


# --- MakeMaker blibdirs section:
blibdirs : $(INST_LIBDIR)$(DFSEP).exists $(INST_ARCHLIB)$(DFSEP).exists $(INST_AUTODIR)$(DFSEP).exists $(INST_ARCHAUTODIR)$(DFSEP).exists $(INST_BIN)$(DFSEP).exists $(INST_SCRIPT)$(DFSEP).exists $(INST_MAN1DIR)$(DFSEP).exists $(INST_MAN3DIR)$(DFSEP).exists
	$(NOECHO) $(NOOP)

# Backwards compat with 6.18 through 6.25
blibdirs.ts : blibdirs
	$(NOECHO) $(NOOP)

$(INST_LIBDIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_LIBDIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_LIBDIR)
	$(NOECHO) $(TOUCH) $(INST_LIBDIR)$(DFSEP).exists

$(INST_ARCHLIB)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHLIB)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHLIB)
	$(NOECHO) $(TOUCH) $(INST_ARCHLIB)$(DFSEP).exists

$(INST_AUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_AUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_AUTODIR)
	$(NOECHO) $(TOUCH) $(INST_AUTODIR)$(DFSEP).exists

$(INST_ARCHAUTODIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_ARCHAUTODIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_ARCHAUTODIR)
	$(NOECHO) $(TOUCH) $(INST_ARCHAUTODIR)$(DFSEP).exists

$(INST_BIN)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_BIN)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_BIN)
	$(NOECHO) $(TOUCH) $(INST_BIN)$(DFSEP).exists

$(INST_SCRIPT)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_SCRIPT)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_SCRIPT)
	$(NOECHO) $(TOUCH) $(INST_SCRIPT)$(DFSEP).exists

$(INST_MAN1DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN1DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN1DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN1DIR)$(DFSEP).exists

$(INST_MAN3DIR)$(DFSEP).exists :: Makefile.PL
	$(NOECHO) $(MKPATH) $(INST_MAN3DIR)
	$(NOECHO) $(CHMOD) $(PERM_DIR) $(INST_MAN3DIR)
	$(NOECHO) $(TOUCH) $(INST_MAN3DIR)$(DFSEP).exists



# --- MakeMaker linkext section:

linkext :: dynamic
	$(NOECHO) $(NOOP)


# --- MakeMaker dlsyms section:


# --- MakeMaker dynamic_bs section:

BOOTSTRAP =


# --- MakeMaker dynamic section:

dynamic :: $(FIRST_MAKEFILE) config $(INST_BOOT) $(INST_DYNAMIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker dynamic_lib section:


# --- MakeMaker static section:

## $(INST_PM) has been moved to the all: target.
## It remains here for awhile to allow for old usage: "make static"
static :: $(FIRST_MAKEFILE) $(INST_STATIC)
	$(NOECHO) $(NOOP)


# --- MakeMaker static_lib section:


# --- MakeMaker manifypods section:

POD2MAN_EXE = $(PERLRUN) "-MExtUtils::Command::MM" -e pod2man "--"
POD2MAN = $(POD2MAN_EXE)


manifypods : pure_all config  \
	804delta.pod \
	Adjuster.pod \
	Animation.pod \
	Balloon.pod \
	Bitmap.pod \
	BrowseEntry.pod \
	Button.pod \
	Canvas.pod \
	Checkbutton.pod \
	Clipboard.pod \
	CmdLine.pod \
	ColorEditor.pod \
	Compound.pod \
	ConfigSpecs.pod \
	DItem.pod \
	Derived.pod \
	Dialog.pod \
	DialogBox.pod \
	DirTree.pod \
	Entry.pod \
	Error.pod \
	ErrorDialog.pod \
	Eventloop.pod \
	FBox.pod \
	FileSelect.pod \
	Font.pod \
	Frame.pod \
	HList.pod \
	IO.pod \
	IconList.pod \
	Image.pod \
	InputO.pod \
	Internals.pod \
	LabFrame.pod \
	Label.pod \
	Labelframe.pod \
	Listbox.pod \
	MainWindow.pod \
	Menu.pod \
	Menu/Item.pod \
	Menubutton.pod \
	Message.pod \
	MsgBox.pod \
	Mwm.pod \
	NoteBook.pod \
	Optionmenu.pod \
	Panedwindow.pod \
	Photo.pod \
	Pixmap.pod \
	Popup.pod \
	ROText.pod \
	Radiobutton.pod \
	Scale.pod \
	Scrollbar.pod \
	Scrolled.pod \
	Spinbox.pod \
	Submethods.pod \
	TList.pod \
	Table.pod \
	Tcl-perl.pod \
	Text.pod \
	TextUndo.pod \
	Tiler.pod \
	TixGrid.pod \
	Toplevel.pod \
	Tree.pod \
	UserGuide.pod \
	Widget.pod \
	WidgetDemo.pod \
	Wm.pod \
	X.pod \
	X11Font.pod \
	Xrm.pod \
	after.pod \
	bind.pod \
	bindtags.pod \
	callbacks.pod \
	chooseColor.pod \
	chooseDirectory.pod \
	composite.pod \
	event.pod \
	exit.pod \
	fileevent.pod \
	focus.pod \
	form.pod \
	getOpenFile.pod \
	grab.pod \
	grid.pod \
	mega.pod \
	messageBox.pod \
	option.pod \
	options.pod \
	overview.pod \
	pTk.pod \
	pack.pod \
	palette.pod \
	place.pod \
	selection.pod \
	send.pod \
	tixWm.pod \
	tkvars.pod \
	widgets.pod
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  804delta.pod $(INST_MAN3DIR)/Tk::804delta.$(MAN3EXT) \
	  Adjuster.pod $(INST_MAN3DIR)/Tk::Adjuster.$(MAN3EXT) \
	  Animation.pod $(INST_MAN3DIR)/Tk::Animation.$(MAN3EXT) \
	  Balloon.pod $(INST_MAN3DIR)/Tk::Balloon.$(MAN3EXT) \
	  Bitmap.pod $(INST_MAN3DIR)/Tk::Bitmap.$(MAN3EXT) \
	  BrowseEntry.pod $(INST_MAN3DIR)/Tk::BrowseEntry.$(MAN3EXT) \
	  Button.pod $(INST_MAN3DIR)/Tk::Button.$(MAN3EXT) \
	  Canvas.pod $(INST_MAN3DIR)/Tk::Canvas.$(MAN3EXT) \
	  Checkbutton.pod $(INST_MAN3DIR)/Tk::Checkbutton.$(MAN3EXT) \
	  Clipboard.pod $(INST_MAN3DIR)/Tk::Clipboard.$(MAN3EXT) \
	  CmdLine.pod $(INST_MAN3DIR)/Tk::CmdLine.$(MAN3EXT) \
	  ColorEditor.pod $(INST_MAN3DIR)/Tk::ColorEditor.$(MAN3EXT) \
	  Compound.pod $(INST_MAN3DIR)/Tk::Compound.$(MAN3EXT) \
	  ConfigSpecs.pod $(INST_MAN3DIR)/Tk::ConfigSpecs.$(MAN3EXT) \
	  DItem.pod $(INST_MAN3DIR)/Tk::DItem.$(MAN3EXT) \
	  Derived.pod $(INST_MAN3DIR)/Tk::Derived.$(MAN3EXT) \
	  Dialog.pod $(INST_MAN3DIR)/Tk::Dialog.$(MAN3EXT) \
	  DialogBox.pod $(INST_MAN3DIR)/Tk::DialogBox.$(MAN3EXT) \
	  DirTree.pod $(INST_MAN3DIR)/Tk::DirTree.$(MAN3EXT) \
	  Entry.pod $(INST_MAN3DIR)/Tk::Entry.$(MAN3EXT) \
	  Error.pod $(INST_MAN3DIR)/Tk::Error.$(MAN3EXT) \
	  ErrorDialog.pod $(INST_MAN3DIR)/Tk::ErrorDialog.$(MAN3EXT) \
	  Eventloop.pod $(INST_MAN3DIR)/Tk::Eventloop.$(MAN3EXT) \
	  FBox.pod $(INST_MAN3DIR)/Tk::FBox.$(MAN3EXT) \
	  FileSelect.pod $(INST_MAN3DIR)/Tk::FileSelect.$(MAN3EXT) \
	  Font.pod $(INST_MAN3DIR)/Tk::Font.$(MAN3EXT) \
	  Frame.pod $(INST_MAN3DIR)/Tk::Frame.$(MAN3EXT) \
	  HList.pod $(INST_MAN3DIR)/Tk::HList.$(MAN3EXT) \
	  IO.pod $(INST_MAN3DIR)/Tk::IO.$(MAN3EXT) \
	  IconList.pod $(INST_MAN3DIR)/Tk::IconList.$(MAN3EXT) \
	  Image.pod $(INST_MAN3DIR)/Tk::Image.$(MAN3EXT) \
	  InputO.pod $(INST_MAN3DIR)/Tk::InputO.$(MAN3EXT) \
	  Internals.pod $(INST_MAN3DIR)/Tk::Internals.$(MAN3EXT) \
	  LabFrame.pod $(INST_MAN3DIR)/Tk::LabFrame.$(MAN3EXT) \
	  Label.pod $(INST_MAN3DIR)/Tk::Label.$(MAN3EXT) \
	  Labelframe.pod $(INST_MAN3DIR)/Tk::Labelframe.$(MAN3EXT) \
	  Listbox.pod $(INST_MAN3DIR)/Tk::Listbox.$(MAN3EXT) \
	  MainWindow.pod $(INST_MAN3DIR)/Tk::MainWindow.$(MAN3EXT) \
	  Menu.pod $(INST_MAN3DIR)/Tk::Menu.$(MAN3EXT) \
	  Menu/Item.pod $(INST_MAN3DIR)/Tk::Menu::Item.$(MAN3EXT) \
	  Menubutton.pod $(INST_MAN3DIR)/Tk::Menubutton.$(MAN3EXT) \
	  Message.pod $(INST_MAN3DIR)/Tk::Message.$(MAN3EXT) \
	  MsgBox.pod $(INST_MAN3DIR)/Tk::MsgBox.$(MAN3EXT) \
	  Mwm.pod $(INST_MAN3DIR)/Tk::Mwm.$(MAN3EXT) \
	  NoteBook.pod $(INST_MAN3DIR)/Tk::NoteBook.$(MAN3EXT) \
	  Optionmenu.pod $(INST_MAN3DIR)/Tk::Optionmenu.$(MAN3EXT) \
	  Panedwindow.pod $(INST_MAN3DIR)/Tk::Panedwindow.$(MAN3EXT) \
	  Photo.pod $(INST_MAN3DIR)/Tk::Photo.$(MAN3EXT) \
	  Pixmap.pod $(INST_MAN3DIR)/Tk::Pixmap.$(MAN3EXT) \
	  Popup.pod $(INST_MAN3DIR)/Tk::Popup.$(MAN3EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  ROText.pod $(INST_MAN3DIR)/Tk::ROText.$(MAN3EXT) \
	  Radiobutton.pod $(INST_MAN3DIR)/Tk::Radiobutton.$(MAN3EXT) \
	  Scale.pod $(INST_MAN3DIR)/Tk::Scale.$(MAN3EXT) \
	  Scrollbar.pod $(INST_MAN3DIR)/Tk::Scrollbar.$(MAN3EXT) \
	  Scrolled.pod $(INST_MAN3DIR)/Tk::Scrolled.$(MAN3EXT) \
	  Spinbox.pod $(INST_MAN3DIR)/Tk::Spinbox.$(MAN3EXT) \
	  Submethods.pod $(INST_MAN3DIR)/Tk::Submethods.$(MAN3EXT) \
	  TList.pod $(INST_MAN3DIR)/Tk::TList.$(MAN3EXT) \
	  Table.pod $(INST_MAN3DIR)/Tk::Table.$(MAN3EXT) \
	  Tcl-perl.pod $(INST_MAN3DIR)/Tk::Tcl-perl.$(MAN3EXT) \
	  Text.pod $(INST_MAN3DIR)/Tk::Text.$(MAN3EXT) \
	  TextUndo.pod $(INST_MAN3DIR)/Tk::TextUndo.$(MAN3EXT) \
	  Tiler.pod $(INST_MAN3DIR)/Tk::Tiler.$(MAN3EXT) \
	  TixGrid.pod $(INST_MAN3DIR)/Tk::TixGrid.$(MAN3EXT) \
	  Toplevel.pod $(INST_MAN3DIR)/Tk::Toplevel.$(MAN3EXT) \
	  Tree.pod $(INST_MAN3DIR)/Tk::Tree.$(MAN3EXT) \
	  UserGuide.pod $(INST_MAN3DIR)/Tk::UserGuide.$(MAN3EXT) \
	  Widget.pod $(INST_MAN3DIR)/Tk::Widget.$(MAN3EXT) \
	  WidgetDemo.pod $(INST_MAN3DIR)/Tk::WidgetDemo.$(MAN3EXT) \
	  Wm.pod $(INST_MAN3DIR)/Tk::Wm.$(MAN3EXT) \
	  X.pod $(INST_MAN3DIR)/Tk::X.$(MAN3EXT) \
	  X11Font.pod $(INST_MAN3DIR)/Tk::X11Font.$(MAN3EXT) \
	  Xrm.pod $(INST_MAN3DIR)/Tk::Xrm.$(MAN3EXT) \
	  after.pod $(INST_MAN3DIR)/Tk::after.$(MAN3EXT) \
	  bind.pod $(INST_MAN3DIR)/Tk::bind.$(MAN3EXT) \
	  bindtags.pod $(INST_MAN3DIR)/Tk::bindtags.$(MAN3EXT) \
	  callbacks.pod $(INST_MAN3DIR)/Tk::callbacks.$(MAN3EXT) \
	  chooseColor.pod $(INST_MAN3DIR)/Tk::chooseColor.$(MAN3EXT) \
	  chooseDirectory.pod $(INST_MAN3DIR)/Tk::chooseDirectory.$(MAN3EXT) \
	  composite.pod $(INST_MAN3DIR)/Tk::composite.$(MAN3EXT) \
	  event.pod $(INST_MAN3DIR)/Tk::event.$(MAN3EXT) \
	  exit.pod $(INST_MAN3DIR)/Tk::exit.$(MAN3EXT) \
	  fileevent.pod $(INST_MAN3DIR)/Tk::fileevent.$(MAN3EXT) \
	  focus.pod $(INST_MAN3DIR)/Tk::focus.$(MAN3EXT) \
	  form.pod $(INST_MAN3DIR)/Tk::form.$(MAN3EXT) \
	  getOpenFile.pod $(INST_MAN3DIR)/Tk::getOpenFile.$(MAN3EXT) \
	  grab.pod $(INST_MAN3DIR)/Tk::grab.$(MAN3EXT) \
	  grid.pod $(INST_MAN3DIR)/Tk::grid.$(MAN3EXT) \
	  mega.pod $(INST_MAN3DIR)/Tk::mega.$(MAN3EXT) \
	  messageBox.pod $(INST_MAN3DIR)/Tk::messageBox.$(MAN3EXT) \
	  option.pod $(INST_MAN3DIR)/Tk::option.$(MAN3EXT) \
	  options.pod $(INST_MAN3DIR)/Tk::options.$(MAN3EXT) \
	  overview.pod $(INST_MAN3DIR)/Tk::overview.$(MAN3EXT) \
	  pTk.pod $(INST_MAN3DIR)/Tk::pTk.$(MAN3EXT) \
	  pack.pod $(INST_MAN3DIR)/Tk::pack.$(MAN3EXT) \
	  palette.pod $(INST_MAN3DIR)/Tk::palette.$(MAN3EXT) \
	  place.pod $(INST_MAN3DIR)/Tk::place.$(MAN3EXT) \
	  selection.pod $(INST_MAN3DIR)/Tk::selection.$(MAN3EXT) \
	  send.pod $(INST_MAN3DIR)/Tk::send.$(MAN3EXT) \
	  tixWm.pod $(INST_MAN3DIR)/Tk::tixWm.$(MAN3EXT) \
	  tkvars.pod $(INST_MAN3DIR)/Tk::tkvars.$(MAN3EXT) 
	$(NOECHO) $(POD2MAN) --section=$(MAN3EXT) --perm_rw=$(PERM_RW) -u \
	  widgets.pod $(INST_MAN3DIR)/Tk::widgets.$(MAN3EXT) 




# --- MakeMaker processPL section:


# --- MakeMaker installbin section:


# --- MakeMaker subdirs section:

# none

# --- MakeMaker clean_subdirs section:
clean_subdirs :
	$(NOECHO) $(NOOP)


# --- MakeMaker clean section:

# Delete temporary files but do not touch installed files. We don't delete
# the Makefile here so a later make realclean still has a makefile to use.

clean :: clean_subdirs
	- $(RM_F) \
	  $(BASEEXT).bso $(BASEEXT).def \
	  $(BASEEXT).exp $(BASEEXT).x \
	  $(BOOTSTRAP) $(INST_ARCHAUTODIR)/extralibs.all \
	  $(INST_ARCHAUTODIR)/extralibs.ld $(MAKE_APERL_FILE) \
	  *$(LIB_EXT) *$(OBJ_EXT) \
	  *perl.core MYMETA.json \
	  MYMETA.yml blibdirs.ts \
	  core core.*perl.*.? \
	  core.[0-9] core.[0-9][0-9] \
	  core.[0-9][0-9][0-9] core.[0-9][0-9][0-9][0-9] \
	  core.[0-9][0-9][0-9][0-9][0-9] lib$(BASEEXT).def \
	  mon.out perl \
	  perl$(EXE_EXT) perl.exe \
	  perlmain.c pm_to_blib \
	  pm_to_blib.ts so_locations \
	  tmon.out 
	- $(RM_RF) \
	  blib 
	  $(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	- $(MV) $(FIRST_MAKEFILE) $(MAKEFILE_OLD) $(DEV_NULL)


# --- MakeMaker realclean_subdirs section:
# so clean is forced to complete before realclean_subdirs runs
realclean_subdirs : clean
	$(NOECHO) $(NOOP)


# --- MakeMaker realclean section:
# Delete temporary files (via clean) and also delete dist files
realclean purge :: realclean_subdirs
	- $(RM_F) \
	  $(FIRST_MAKEFILE) $(MAKEFILE_OLD) 
	- $(RM_RF) \
	  $(DISTVNAME) 


# --- MakeMaker metafile section:
metafile : create_distdir
	$(NOECHO) $(ECHO) Generating META.yml
	$(NOECHO) $(ECHO) '---' > META_new.yml
	$(NOECHO) $(ECHO) 'abstract: unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'author:' >> META_new.yml
	$(NOECHO) $(ECHO) '  - unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'build_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'configure_requires:' >> META_new.yml
	$(NOECHO) $(ECHO) '  ExtUtils::MakeMaker: '\''0'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'dynamic_config: 1' >> META_new.yml
	$(NOECHO) $(ECHO) 'generated_by: '\''ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'license: unknown' >> META_new.yml
	$(NOECHO) $(ECHO) 'meta-spec:' >> META_new.yml
	$(NOECHO) $(ECHO) '  url: http://module-build.sourceforge.net/META-spec-v1.4.html' >> META_new.yml
	$(NOECHO) $(ECHO) '  version: '\''1.4'\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'name: Tk-pod' >> META_new.yml
	$(NOECHO) $(ECHO) 'no_index:' >> META_new.yml
	$(NOECHO) $(ECHO) '  directory:' >> META_new.yml
	$(NOECHO) $(ECHO) '    - t' >> META_new.yml
	$(NOECHO) $(ECHO) '    - inc' >> META_new.yml
	$(NOECHO) $(ECHO) 'version: '\'''\''' >> META_new.yml
	$(NOECHO) $(ECHO) 'x_serialization_backend: '\''CPAN::Meta::YAML version 0.018'\''' >> META_new.yml
	-$(NOECHO) $(MV) META_new.yml $(DISTVNAME)/META.yml
	$(NOECHO) $(ECHO) Generating META.json
	$(NOECHO) $(ECHO) '{' > META_new.json
	$(NOECHO) $(ECHO) '   "abstract" : "unknown",' >> META_new.json
	$(NOECHO) $(ECHO) '   "author" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "unknown"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "dynamic_config" : 1,' >> META_new.json
	$(NOECHO) $(ECHO) '   "generated_by" : "ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010",' >> META_new.json
	$(NOECHO) $(ECHO) '   "license" : [' >> META_new.json
	$(NOECHO) $(ECHO) '      "unknown"' >> META_new.json
	$(NOECHO) $(ECHO) '   ],' >> META_new.json
	$(NOECHO) $(ECHO) '   "meta-spec" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",' >> META_new.json
	$(NOECHO) $(ECHO) '      "version" : "2"' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "name" : "Tk-pod",' >> META_new.json
	$(NOECHO) $(ECHO) '   "no_index" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "directory" : [' >> META_new.json
	$(NOECHO) $(ECHO) '         "t",' >> META_new.json
	$(NOECHO) $(ECHO) '         "inc"' >> META_new.json
	$(NOECHO) $(ECHO) '      ]' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "prereqs" : {' >> META_new.json
	$(NOECHO) $(ECHO) '      "build" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      },' >> META_new.json
	$(NOECHO) $(ECHO) '      "configure" : {' >> META_new.json
	$(NOECHO) $(ECHO) '         "requires" : {' >> META_new.json
	$(NOECHO) $(ECHO) '            "ExtUtils::MakeMaker" : "0"' >> META_new.json
	$(NOECHO) $(ECHO) '         }' >> META_new.json
	$(NOECHO) $(ECHO) '      }' >> META_new.json
	$(NOECHO) $(ECHO) '   },' >> META_new.json
	$(NOECHO) $(ECHO) '   "release_status" : "stable",' >> META_new.json
	$(NOECHO) $(ECHO) '   "version" : "",' >> META_new.json
	$(NOECHO) $(ECHO) '   "x_serialization_backend" : "JSON::PP version 2.27400_02"' >> META_new.json
	$(NOECHO) $(ECHO) '}' >> META_new.json
	-$(NOECHO) $(MV) META_new.json $(DISTVNAME)/META.json


# --- MakeMaker signature section:
signature :
	cpansign -s


# --- MakeMaker dist_basics section skipped.

# --- MakeMaker dist_core section skipped.

# --- MakeMaker distdir section skipped.

# --- MakeMaker dist_test section skipped.

# --- MakeMaker dist_ci section skipped.

# --- MakeMaker distmeta section:
distmeta : create_distdir metafile
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -e q{META.yml};' \
	  -e 'eval { maniadd({q{META.yml} => q{Module YAML meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.yml to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'exit unless -f q{META.json};' \
	  -e 'eval { maniadd({q{META.json} => q{Module JSON meta-data (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add META.json to MANIFEST: $${'\''@'\''}"' --



# --- MakeMaker distsignature section:
distsignature : distmeta
	$(NOECHO) cd $(DISTVNAME) && $(ABSPERLRUN) -MExtUtils::Manifest=maniadd -e 'eval { maniadd({q{SIGNATURE} => q{Public-key signature (added by MakeMaker)}}) }' \
	  -e '    or die "Could not add SIGNATURE to MANIFEST: $${'\''@'\''}"' --
	$(NOECHO) cd $(DISTVNAME) && $(TOUCH) SIGNATURE
	cd $(DISTVNAME) && cpansign -s



# --- MakeMaker install section skipped.

# --- MakeMaker force section:
# Phony target to force checking subdirectories.
FORCE :
	$(NOECHO) $(NOOP)


# --- MakeMaker perldepend section:


# --- MakeMaker makefile section:
# We take a very conservative approach here, but it's worth it.
# We move Makefile to Makefile.old here to avoid gnu make looping.
$(FIRST_MAKEFILE) : Makefile.PL $(CONFIGDEP)
	$(NOECHO) $(ECHO) "Makefile out-of-date with respect to $?"
	$(NOECHO) $(ECHO) "Cleaning current config before rebuilding Makefile..."
	-$(NOECHO) $(RM_F) $(MAKEFILE_OLD)
	-$(NOECHO) $(MV)   $(FIRST_MAKEFILE) $(MAKEFILE_OLD)
	- $(MAKE) $(USEMAKEFILE) $(MAKEFILE_OLD) clean $(DEV_NULL)
	$(PERLRUN) Makefile.PL "BINARY_LOCATION=x86_64-linux-gnu-thread-multi/Tk804.033-PPM.tar.gz"
	$(NOECHO) $(ECHO) "==> Your Makefile has been rebuilt. <=="
	$(NOECHO) $(ECHO) "==> Please rerun the $(MAKE) command.  <=="
	$(FALSE)



# --- MakeMaker staticmake section:

# --- MakeMaker makeaperl section ---
MAP_TARGET    = ../perl
FULLPERL      = "/usr/bin/perl"
MAP_PERLINC   = "-I../blib/arch" "-I../blib/lib" "-I/usr/lib/x86_64-linux-gnu/perl/5.26" "-I/usr/share/perl/5.26"


# --- MakeMaker test section:
TEST_VERBOSE=0
TEST_TYPE=test_$(LINKTYPE)
TEST_FILE = test.pl
TEST_FILES = 
TESTDB_SW = -d

testdb :: testdb_$(LINKTYPE)
	$(NOECHO) $(NOOP)

test :: $(TEST_TYPE)
	$(NOECHO) $(NOOP)

# Occasionally we may face this degenerate target:
test_ : test_dynamic
	$(NOECHO) $(NOOP)

subdirs-test_dynamic :: dynamic pure_all

testdb_dynamic test_dynamic :: subdirs-test_dynamic
	$(NOECHO) $(ECHO) 'No tests defined for $(NAME) extension.'

subdirs-test_static :: static pure_all

testdb_static test_static :: subdirs-test_static
	$(NOECHO) $(ECHO) 'No tests defined for $(NAME) extension.'



# --- MakeMaker ppd section:
# Creates a PPD (Perl Package Description) for a binary distribution.
ppd :
	$(NOECHO) $(ECHO) '<SOFTPKG NAME="Tk-pod" VERSION="">' > Tk-pod.ppd
	$(NOECHO) $(ECHO) '    <ABSTRACT></ABSTRACT>' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '    <AUTHOR></AUTHOR>' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '    <IMPLEMENTATION>' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '        <ARCHITECTURE NAME="x86_64-linux-gnu-thread-multi-5.26" />' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '        <CODEBASE HREF="" />' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '    </IMPLEMENTATION>' >> Tk-pod.ppd
	$(NOECHO) $(ECHO) '</SOFTPKG>' >> Tk-pod.ppd


# --- MakeMaker pm_to_blib section:

pm_to_blib : $(FIRST_MAKEFILE) $(TO_INST_PM)
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  '804delta.pod' '$(INST_LIB)/Tk/804delta.pod' \
	  'Adjuster.pod' '$(INST_LIB)/Tk/Adjuster.pod' \
	  'Animation.pod' '$(INST_LIB)/Tk/Animation.pod' \
	  'Balloon.pod' '$(INST_LIB)/Tk/Balloon.pod' \
	  'Bitmap.pod' '$(INST_LIB)/Tk/Bitmap.pod' \
	  'BrowseEntry.pod' '$(INST_LIB)/Tk/BrowseEntry.pod' \
	  'Button.pod' '$(INST_LIB)/Tk/Button.pod' \
	  'Canvas.pod' '$(INST_LIB)/Tk/Canvas.pod' \
	  'Checkbutton.pod' '$(INST_LIB)/Tk/Checkbutton.pod' \
	  'Clipboard.pod' '$(INST_LIB)/Tk/Clipboard.pod' \
	  'CmdLine.pod' '$(INST_LIB)/Tk/CmdLine.pod' \
	  'ColorEditor.pod' '$(INST_LIB)/Tk/ColorEditor.pod' \
	  'Compound.pod' '$(INST_LIB)/Tk/Compound.pod' \
	  'ConfigSpecs.pod' '$(INST_LIB)/Tk/ConfigSpecs.pod' \
	  'DItem.pod' '$(INST_LIB)/Tk/DItem.pod' \
	  'Derived.pod' '$(INST_LIB)/Tk/Derived.pod' \
	  'Dialog.pod' '$(INST_LIB)/Tk/Dialog.pod' \
	  'DialogBox.pod' '$(INST_LIB)/Tk/DialogBox.pod' \
	  'DirTree.pod' '$(INST_LIB)/Tk/DirTree.pod' \
	  'Entry.pod' '$(INST_LIB)/Tk/Entry.pod' \
	  'Error.pod' '$(INST_LIB)/Tk/Error.pod' \
	  'ErrorDialog.pod' '$(INST_LIB)/Tk/ErrorDialog.pod' \
	  'Eventloop.pod' '$(INST_LIB)/Tk/Eventloop.pod' \
	  'FBox.pod' '$(INST_LIB)/Tk/FBox.pod' \
	  'FileSelect.pod' '$(INST_LIB)/Tk/FileSelect.pod' \
	  'Font.pod' '$(INST_LIB)/Tk/Font.pod' \
	  'Frame.pod' '$(INST_LIB)/Tk/Frame.pod' \
	  'HList.pod' '$(INST_LIB)/Tk/HList.pod' \
	  'IO.pod' '$(INST_LIB)/Tk/IO.pod' \
	  'IconList.pod' '$(INST_LIB)/Tk/IconList.pod' \
	  'Image.pod' '$(INST_LIB)/Tk/Image.pod' \
	  'InputO.pod' '$(INST_LIB)/Tk/InputO.pod' \
	  'Internals.pod' '$(INST_LIB)/Tk/Internals.pod' \
	  'LabFrame.pod' '$(INST_LIB)/Tk/LabFrame.pod' \
	  'Label.pod' '$(INST_LIB)/Tk/Label.pod' \
	  'Labelframe.pod' '$(INST_LIB)/Tk/Labelframe.pod' \
	  'Listbox.pod' '$(INST_LIB)/Tk/Listbox.pod' \
	  'MainWindow.pod' '$(INST_LIB)/Tk/MainWindow.pod' \
	  'Menu.pod' '$(INST_LIB)/Tk/Menu.pod' \
	  'Menu/Item.pod' '$(INST_LIB)/Tk/Menu/Item.pod' \
	  'Menubutton.pod' '$(INST_LIB)/Tk/Menubutton.pod' \
	  'Message.pod' '$(INST_LIB)/Tk/Message.pod' \
	  'MsgBox.pod' '$(INST_LIB)/Tk/MsgBox.pod' \
	  'Mwm.pod' '$(INST_LIB)/Tk/Mwm.pod' \
	  'NoteBook.pod' '$(INST_LIB)/Tk/NoteBook.pod' \
	  'Optionmenu.pod' '$(INST_LIB)/Tk/Optionmenu.pod' \
	  'Panedwindow.pod' '$(INST_LIB)/Tk/Panedwindow.pod' \
	  'Photo.pod' '$(INST_LIB)/Tk/Photo.pod' \
	  'Pixmap.pod' '$(INST_LIB)/Tk/Pixmap.pod' \
	  'Popup.pod' '$(INST_LIB)/Tk/Popup.pod' \
	  'ROText.pod' '$(INST_LIB)/Tk/ROText.pod' \
	  'Radiobutton.pod' '$(INST_LIB)/Tk/Radiobutton.pod' \
	  'Scale.pod' '$(INST_LIB)/Tk/Scale.pod' \
	  'Scrollbar.pod' '$(INST_LIB)/Tk/Scrollbar.pod' \
	  'Scrolled.pod' '$(INST_LIB)/Tk/Scrolled.pod' \
	  'Spinbox.pod' '$(INST_LIB)/Tk/Spinbox.pod' \
	  'Submethods.pod' '$(INST_LIB)/Tk/Submethods.pod' 
	$(NOECHO) $(ABSPERLRUN) -MExtUtils::Install -e 'pm_to_blib({@ARGV}, '\''$(INST_LIB)/auto'\'', q[$(PM_FILTER)], '\''$(PERM_DIR)'\'')' -- \
	  'TList.pod' '$(INST_LIB)/Tk/TList.pod' \
	  'Table.pod' '$(INST_LIB)/Tk/Table.pod' \
	  'Tcl-perl.pod' '$(INST_LIB)/Tk/Tcl-perl.pod' \
	  'Text.pod' '$(INST_LIB)/Tk/Text.pod' \
	  'TextUndo.pod' '$(INST_LIB)/Tk/TextUndo.pod' \
	  'Tiler.pod' '$(INST_LIB)/Tk/Tiler.pod' \
	  'TixGrid.pod' '$(INST_LIB)/Tk/TixGrid.pod' \
	  'Toplevel.pod' '$(INST_LIB)/Tk/Toplevel.pod' \
	  'Tree.pod' '$(INST_LIB)/Tk/Tree.pod' \
	  'UserGuide.pod' '$(INST_LIB)/Tk/UserGuide.pod' \
	  'Widget.pod' '$(INST_LIB)/Tk/Widget.pod' \
	  'WidgetDemo.pod' '$(INST_LIB)/Tk/WidgetDemo.pod' \
	  'Wm.pod' '$(INST_LIB)/Tk/Wm.pod' \
	  'X.pod' '$(INST_LIB)/Tk/X.pod' \
	  'X11Font.pod' '$(INST_LIB)/Tk/X11Font.pod' \
	  'Xrm.pod' '$(INST_LIB)/Tk/Xrm.pod' \
	  'after.pod' '$(INST_LIB)/Tk/after.pod' \
	  'bind.pod' '$(INST_LIB)/Tk/bind.pod' \
	  'bindtags.pod' '$(INST_LIB)/Tk/bindtags.pod' \
	  'callbacks.pod' '$(INST_LIB)/Tk/callbacks.pod' \
	  'chooseColor.pod' '$(INST_LIB)/Tk/chooseColor.pod' \
	  'chooseDirectory.pod' '$(INST_LIB)/Tk/chooseDirectory.pod' \
	  'composite.pod' '$(INST_LIB)/Tk/composite.pod' \
	  'event.pod' '$(INST_LIB)/Tk/event.pod' \
	  'exit.pod' '$(INST_LIB)/Tk/exit.pod' \
	  'fileevent.pod' '$(INST_LIB)/Tk/fileevent.pod' \
	  'focus.pod' '$(INST_LIB)/Tk/focus.pod' \
	  'form.pod' '$(INST_LIB)/Tk/form.pod' \
	  'getOpenFile.pod' '$(INST_LIB)/Tk/getOpenFile.pod' \
	  'grab.pod' '$(INST_LIB)/Tk/grab.pod' \
	  'grid.pod' '$(INST_LIB)/Tk/grid.pod' \
	  'mega.pod' '$(INST_LIB)/Tk/mega.pod' \
	  'messageBox.pod' '$(INST_LIB)/Tk/messageBox.pod' \
	  'option.pod' '$(INST_LIB)/Tk/option.pod' \
	  'options.pod' '$(INST_LIB)/Tk/options.pod' \
	  'overview.pod' '$(INST_LIB)/Tk/overview.pod' \
	  'pTk.pod' '$(INST_LIB)/Tk/pTk.pod' \
	  'pack.pod' '$(INST_LIB)/Tk/pack.pod' \
	  'palette.pod' '$(INST_LIB)/Tk/palette.pod' \
	  'place.pod' '$(INST_LIB)/Tk/place.pod' \
	  'selection.pod' '$(INST_LIB)/Tk/selection.pod' \
	  'send.pod' '$(INST_LIB)/Tk/send.pod' \
	  'tixWm.pod' '$(INST_LIB)/Tk/tixWm.pod' \
	  'tkvars.pod' '$(INST_LIB)/Tk/tkvars.pod' \
	  'widgets.pod' '$(INST_LIB)/Tk/widgets.pod' 
	$(NOECHO) $(TOUCH) pm_to_blib


# --- MakeMaker selfdocument section:

# here so even if top_targets is overridden, these will still be defined
# gmake will silently still work if any are .PHONY-ed but nmake won't

static ::
	$(NOECHO) $(NOOP)

dynamic ::
	$(NOECHO) $(NOOP)

config ::
	$(NOECHO) $(NOOP)


# --- MakeMaker postamble section:

html ::
	@echo "Sorry no HTML building yet"


# End.
